### ISSUE TITLE
钓鱼奖励触发问题

### ISSUE THREAD

**Issue by QiaTaTa** [killerprojecte/UltraLucky#1]
![1682502166365](https://user-images.githubusercontent.com/54050103/234537156-9e206788-71c0-40e2-888b-3a5be25b97ff.jpg)
玩家非钓鱼状态下也会触发奖励，钓到人或者生物也会有奖励，导致玩家可以开始连点器刷奖励。

**Comment by killerprojecte** [comment]
Commit abfbb90 fixed the issue
